// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYfCbGYrEzXQKYBS0YrL_v-F7eTiZg3M',
    appId: '1:911733523727:web:22e51d5cd3b7be46412a7a',
    messagingSenderId: '911733523727',
    projectId: 'workagendafinalproje',
    authDomain: 'workagendafinalproje.firebaseapp.com',
    storageBucket: 'workagendafinalproje.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IdS4PBKNprdeOx03OP7wh5LYTMtQ9OI',
    appId: '1:911733523727:android:c19e07d4386b91d0412a7a',
    messagingSenderId: '911733523727',
    projectId: 'workagendafinalproje',
    storageBucket: 'workagendafinalproje.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Ag9DXkhTF7Jq_j7QZ5ib4IoNWdKFJgM',
    appId: '1:911733523727:ios:30173f09945bf96c412a7a',
    messagingSenderId: '911733523727',
    projectId: 'workagendafinalproje',
    storageBucket: 'workagendafinalproje.firebasestorage.app',
    iosBundleId: 'com.example.mobilProje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Ag9DXkhTF7Jq_j7QZ5ib4IoNWdKFJgM',
    appId: '1:911733523727:ios:30173f09945bf96c412a7a',
    messagingSenderId: '911733523727',
    projectId: 'workagendafinalproje',
    storageBucket: 'workagendafinalproje.firebasestorage.app',
    iosBundleId: 'com.example.mobilProje1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuYfCbGYrEzXQKYBS0YrL_v-F7eTiZg3M',
    appId: '1:911733523727:web:ba81870904e7c138412a7a',
    messagingSenderId: '911733523727',
    projectId: 'workagendafinalproje',
    authDomain: 'workagendafinalproje.firebaseapp.com',
    storageBucket: 'workagendafinalproje.firebasestorage.app',
  );
}
